from cellpose import io, models, metrics, plot
from pathlib import Path
from subprocess import check_output, STDOUT
import os, shutil
import numpy as np


def test_shape_2D():
    """
    Tests the shape of the output masks generated by the Cellpose model on a 2D image.

    This method creates a 2D image filled with zeros and then uses the Cellpose model
    to evaluate the image, checking that the output mask has the expected shape.

    Parameters:
    None

    Returns:
    None
    """
    img = np.zeros((224, 1, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[0, 0], channel_axis=1)
    assert masks.shape == (224, 224)


def test_shape_3D():
    """
    Tests the functionality of a 3D shape detection model using a predefined 3D image.

    This method creates a 3D image of zeros, initializes a Cellpose model designed for
    cytoplasmic segmentation, and evaluates the model on the generated image. It then
    asserts that the shape of the resulting masks is as expected.

    Parameters:
        None

    Returns:
        None
    """
    img = np.zeros((224, 224, 1, 5, 1))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], channel_axis=None, z_axis=3
    )
    assert masks.shape == (5, 224, 224)


def test_shape_stitch():
    """
    Tests the shape of the masks produced by the Cellpose model when evaluating an image.

    This method creates a test image of zeros and evaluates it using the Cellpose model
    to ensure that the output masks have the expected shape.

    Returns:
        None: This method does not return a value; it asserts if the output shape is correct.
    """
    img = np.zeros((5, 224, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], stitch_threshold=0.9
    )
    assert masks.shape == (5, 224, 224)


def test_shape_2D_2chan():
    """
    Tests the functionality of the Cellpose model for 2D images with 2 channels.

    This method initializes a zero image with a specific shape and evaluates the Cellpose model on it. It checks that the output mask has the expected shape.

    Returns:
        None: This method does not return any value, but asserts that the output mask has the correct shape.
    """
    img = np.zeros((224, 3, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[2, 1], channel_axis=1)
    assert masks.shape == (224, 224)
