from cellpose import io, models, metrics, plot
from pathlib import Path
from subprocess import check_output, STDOUT
import os, shutil
import numpy as np


def test_shape_2D():
    """
    Tests the functionality of the Cellpose model on a 2D image with specific parameters.

    This method initializes a 2D image and runs the Cellpose model to evaluate the segmentation masks. The method ensures that the output masks have the expected shape.

    Args:
        None

    Returns:
        None
    """
    img = np.zeros((224, 1, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[0, 0], channel_axis=1)
    assert masks.shape == (224, 224)


def test_shape_3D():
    """
    Tests the shape of the masks generated by the Cellpose model for 3D images.

    This method creates a dummy 3D image with specific dimensions and passes it through
    the Cellpose model to evaluate the output masks. It asserts that the shape of the
    output masks matches the expected dimensions.

    Returns:
        None: This method does not return any value.
    """
    img = np.zeros((224, 224, 1, 5, 1))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], channel_axis=None, z_axis=3
    )
    assert masks.shape == (5, 224, 224)


def test_shape_stitch():
    """
    No valid docstring found.
    """
    img = np.zeros((5, 224, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], stitch_threshold=0.9
    )
    assert masks.shape == (5, 224, 224)


def test_shape_2D_2chan():
    """

    Tests the shape of the output masks generated by the Cellpose model
    for a 2D image with 2 channels.

    This method initializes a 2D image with a specific shape and
    evaluates the Cellpose model on that image, asserting that the
    shape of the resulting masks matches the expected output shape.

    Args:
        None

    Returns:
        None
    """
    img = np.zeros((224, 3, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[2, 1], channel_axis=1)
    assert masks.shape == (224, 224)
